$(document).ready(function(){
    $('#homeIcon').click(function(){
        window.location.href="./home.html";
    })
    $('#mapIcon').click(function(){
        window.location.href="./map.html";
    })
    $('#infoBoardIcon').click(function(){
        window.location.href="./infoBoard.html";
    })
    $('#freeBoardIcon').click(function(){
        window.location.href="./freeBoard.html";
    })
    $('.backIcon').click(function(){
        history.go(-1);
    })
})       