$(document).ready(function(){
$('#freeBoardWriteIcon').click(function(){
    //권한검사
    window.location.href="./write.html";
})
$('#freeBoardSearchIcon').click(function(){
    window.location.href="./search.html";
})
})